# Generated by Django 4.2 on 2023-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_snack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
