# Generated by Django 4.2 on 2023-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_favorite_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_snack',
            new_name='description',
        ),
    ]
